steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - backend/docker-compose.dev.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - backend/docker-compose.dev.yaml
      - push

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/tp-backend',
        'tp-backend-sha256-1=asia.gcr.io/main-project-leokim1178/tp-backend:0.0.3',
      ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=leo-tp-cluster
